<?php

/**
 * BaseFileToUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property string $url
 * @property File $File
 * 
 * @method integer   getFileId()  Returns the current record's "file_id" value
 * @method string    getUrl()     Returns the current record's "url" value
 * @method File      getFile()    Returns the current record's "File" value
 * @method FileToUrl setFileId()  Sets the current record's "file_id" value
 * @method FileToUrl setUrl()     Sets the current record's "url" value
 * @method FileToUrl setFile()    Sets the current record's "File" value
 * 
 * @package    Circle
 * @subpackage model
 * @author     Sanjeevan Ambalavanar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileToUrl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_to_url');
        $this->hasColumn('file_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}