<?php

/**
 * FileToStoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileToStoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FileToStoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FileToStory');
    }
}