<?php

/**
 * FileToUrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileToUrlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FileToUrlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FileToUrl');
    }
}